# USANDO A IMAGEM BASE DO NODE.JS 22
FROM node:22

# DEFINIR O DIRETORIO DE TRABALHO DENTRO DO CONTAINER
WORKDIR /app

# COPIANDO PACKAGE.JSON E PACKAGE-LOCK.JSON
COPY package*.json ./

# INSTALANDO DEPENDENCIAS: VAI INSTALAR OS MODULOS 
# QUE O NODE.JS IRA UTILIZAR COMO O EXPRESS
RUN npm install

#COPIANDO OS ARQUIVOS DA APLICAÇAO
COPY . .

# EXPONDO A PORTA QUE A API VAI RODAR
EXPOSE 5000

# COMANDO PARA RODAR A APLICAÇAO
CMD ["node", "index.js"]